// PLAYER BOARD ACTIONS
export const DELETE_PLAYER_BOARD = 'DELETE_PLAYER_BOARD';
export const SET_PLAYER_BOARD = 'SET_PLAYER_BOARD';

// PLAYER NAME ACTIONS
export const DELETE_PLAYER_NAME = 'DELETE_PLAYER_NAME';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';

// PLAYER SHIPS ACTIONS
export const DELETE_PLAYER_SHIPS = 'DELETE_PLAYER_SHIPS';
export const SET_PLAYER_SHIPS = 'SET_PLAYER_SHIPS';

// GAME IS RUNNING ACTIONS
export const SET_GAME_IS_RUNNING = 'SET_GAME_IS_RUNNING';

// GAME RESULT ACTIONS
export const SET_GAME_RESULT = 'SET_GAME_RESULT';
