// PLAYER BOARD ACTIONS
export const SET_PLAYER_BOARD = 'SET_PLAYER_BOARD';
export const DELETE_PLAYER_BOARD = 'DELETE_PLAYER_BOARD';

// PLAYER NAME ACTIONS
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const DELETE_PLAYER_NAME = 'DELETE_PLAYER_NAME';
